package screentime;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

public class ScreenTimee extends JFrame {
    private int totalTime = 0;
    private static ArrayList<Project> projects;
    private static ArrayList<Employee> employees;
    private ArrayList<Activity> activities;
    private ManagementEmployees me;
    private ProjectManagement pm;
    
    public ScreenTimee(ArrayList<Employee> employees, ArrayList<Project> projects) {
        activities = new ArrayList<>();
        this.employees = employees;
        this.projects = projects;

        if (pm != null && pm.getProjects() != null) {
            projects.addAll(pm.getProjects());
        }
        if (me != null && me.getEmployees() != null) {
            employees.addAll(me.getEmployees());
        }

        initComponents();
        setupTable();
        populateComboBoxes();
    }
    /**
     * Creates new form tracker
     */
    private void setupTable() {
        String[] columns = {"Activity Name", "Description", "Daily Target", "Duration", "Employee ID", "Project ID"};
        Table.setModel(new DefaultTableModel(new Object[][]{}, columns));
        Table.setEnabled(true); // Mengaktifkan tabel
        jScrollPane1.setEnabled(true);
    }

    private void populateComboBoxes() {
        IDBox.removeAllItems();
        jComboBox2.removeAllItems();

        for (Employee employee : employees) {
            IDBox.addItem(String.valueOf(employee.getId()));
        }
        for (Project project : projects) {
            jComboBox2.addItem(String.valueOf(project.getId()));
        }
        IDBox.setSelectedIndex(-1); 
        jComboBox2.setSelectedIndex(-1); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        ScreenTimeTracker = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        txtActivityName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDailyTarget = new javax.swing.JLabel();
        IDBox = new javax.swing.JComboBox<>();
        txtTimeTotal1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtDurationMinutes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddActivity = new javax.swing.JButton();
        txtActivity = new javax.swing.JTextField();
        txtTarget = new javax.swing.JTextField();
        txtUserName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtTimeTotal = new javax.swing.JLabel();
        tableActivities = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(684, 569));
        getContentPane().setLayout(null);

        BtnBack.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        BtnBack.setForeground(new java.awt.Color(102, 0, 153));
        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBack);
        BtnBack.setBounds(20, 20, 72, 31);

        ScreenTimeTracker.setFont(new java.awt.Font("Sylfaen", 1, 25)); // NOI18N
        ScreenTimeTracker.setForeground(new java.awt.Color(255, 255, 255));
        ScreenTimeTracker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScreenTimeTracker.setText("SCREEN TIME TRACKER");
        getContentPane().add(ScreenTimeTracker);
        ScreenTimeTracker.setBounds(0, 20, 684, 34);

        jScrollPane1.setEnabled(false);
        jScrollPane1.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Activity  Name", "Description", "Daily Target", "Duration", "Employee ID", "Project ID"
            }
        ));
        Table.setEnabled(false);
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 390, 650, 90);

        txtActivityName.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtActivityName.setForeground(new java.awt.Color(255, 204, 255));
        txtActivityName.setText("Description");
        getContentPane().add(txtActivityName);
        txtActivityName.setBounds(120, 120, 120, 30);

        jLabel1.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 255));
        jLabel1.setText("Project ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 260, 130, 20);

        txtDailyTarget.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtDailyTarget.setForeground(new java.awt.Color(255, 204, 255));
        txtDailyTarget.setText("Daily Target");
        getContentPane().add(txtDailyTarget);
        txtDailyTarget.setBounds(120, 160, 100, 30);

        IDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDBoxActionPerformed(evt);
            }
        });
        getContentPane().add(IDBox);
        IDBox.setBounds(370, 220, 200, 20);

        txtTimeTotal1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        txtTimeTotal1.setForeground(new java.awt.Color(255, 204, 255));
        txtTimeTotal1.setText("0");
        getContentPane().add(txtTimeTotal1);
        txtTimeTotal1.setBounds(410, 490, 40, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(370, 300, 80, 22);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(370, 260, 200, 20);

        txtDurationMinutes.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtDurationMinutes.setForeground(new java.awt.Color(255, 204, 255));
        txtDurationMinutes.setText("Employee ID");
        getContentPane().add(txtDurationMinutes);
        txtDurationMinutes.setBounds(120, 220, 160, 25);

        jLabel3.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 255));
        jLabel3.setText("Duration");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 300, 90, 30);

        AddActivity.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        AddActivity.setForeground(new java.awt.Color(102, 0, 153));
        AddActivity.setText("Add Activity");
        AddActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActivityActionPerformed(evt);
            }
        });
        getContentPane().add(AddActivity);
        AddActivity.setBounds(530, 330, 130, 30);

        txtActivity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActivityActionPerformed(evt);
            }
        });
        getContentPane().add(txtActivity);
        txtActivity.setBounds(370, 120, 197, 30);

        txtTarget.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTargetActionPerformed(evt);
            }
        });
        getContentPane().add(txtTarget);
        txtTarget.setBounds(370, 160, 197, 30);

        txtUserName.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(255, 204, 255));
        txtUserName.setText("Activity Name");
        getContentPane().add(txtUserName);
        txtUserName.setBounds(120, 80, 120, 30);

        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(370, 80, 200, 30);

        txtTimeTotal.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        txtTimeTotal.setForeground(new java.awt.Color(255, 204, 255));
        txtTimeTotal.setText("Time Total");
        getContentPane().add(txtTimeTotal);
        txtTimeTotal.setBounds(250, 490, 130, 32);

        tableActivities.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        tableActivities.setForeground(new java.awt.Color(255, 204, 255));
        tableActivities.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableActivities.setText("List of Activities");
        getContentPane().add(tableActivities);
        tableActivities.setBounds(10, 360, 650, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/screentime/Desktop - 1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -1990, 684, 2570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTargetActionPerformed
        String description = txtTarget.getText().trim();
        if (!description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Target harian diubah menjadi: " + description, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtTargetActionPerformed

    private void txtActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActivityActionPerformed
        String activityName = txtActivity.getText().trim();
        if (!activityName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Deskripsi aktivitas diubah menjadi: " + activityName, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtActivityActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        String name = txtName.getText().trim();
        if (!name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama aktivitas diubah menjadi: " + name, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtNameActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        MainLayer mainLayer = new MainLayer();
        mainLayer.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_BtnBackActionPerformed

    private void IDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDBoxActionPerformed
        String selectedEmployee = IDBox.getSelectedItem() != null ? IDBox.getSelectedItem().toString() : "";
        if (!selectedEmployee.isEmpty() && !selectedEmployee.equals("Pilih Karyawan")) {
//            JOptionPane.showMessageDialog(this, "Karyawan dipilih: " + selectedEmployee, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_IDBoxActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String selectedProject = jComboBox2.getSelectedItem() != null ? jComboBox2.getSelectedItem().toString() : "";
        if (!selectedProject.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Proyek dipilih: " + selectedProject, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String duration = jTextField1.getText().trim();
        if (!duration.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Durasi diubah menjadi: " + duration, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void AddActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActivityActionPerformed
        String activityName = txtName.getText().trim();
        String description = txtActivity.getText().trim();
        String dailyTarget = txtTarget.getText().trim();
        String duration = jTextField1.getText().trim();
        String employeeId = IDBox.getSelectedItem() != null ? IDBox.getSelectedItem().toString() : "";
        String projectId = jComboBox2.getSelectedItem() != null ? jComboBox2.getSelectedItem().toString() : "";

        if (activityName.isEmpty() || description.isEmpty() || dailyTarget.isEmpty() || duration.isEmpty() || employeeId.isEmpty() || projectId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int durationValue = Integer.parseInt(duration);
            int dailyTargetValue = Integer.parseInt(dailyTarget);
            if (durationValue <= 0 || dailyTargetValue <= 0) {
                JOptionPane.showMessageDialog(this, "Durasi dan Target Harian harus lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Activity activity = new Activity(activityName, durationValue);
            activities.add(activity);

            DefaultTableModel model = (DefaultTableModel) Table.getModel();
            model.addRow(new Object[]{activityName, description, dailyTarget, duration, employeeId, projectId});

            totalTime += durationValue;
            txtTimeTotal1.setText(String.valueOf(totalTime));

            // Tampilkan pop-up konfirmasi karyawan yang dipilih setelah aktivitas ditambahkan
//            JOptionPane.showMessageDialog(this, "Karyawan dipilih: " + employeeId, "Info", JOptionPane.INFORMATION_MESSAGE);

            txtName.setText("");
            txtActivity.setText("");
            txtTarget.setText("");
            jTextField1.setText("");
            IDBox.setSelectedIndex(-1);
            jComboBox2.setSelectedIndex(-1);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Durasi dan Target Harian harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddActivityActionPerformed

    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {
            ManagementEmployees me = new ManagementEmployees();
            ProjectManagement pm = new ProjectManagement();
            ScreenTimee screenTimee = new ScreenTimee(me.getEmployees(), pm.getProjects()); // Baris ini memicu error
            screenTimee.setVisible(true);
            me.setVisible(false);
            pm.setVisible(false);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddActivity;
    private javax.swing.JButton BtnBack;
    private javax.swing.JComboBox<String> IDBox;
    private javax.swing.JLabel ScreenTimeTracker;
    private javax.swing.JTable Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel tableActivities;
    private javax.swing.JTextField txtActivity;
    private javax.swing.JLabel txtActivityName;
    private javax.swing.JLabel txtDailyTarget;
    private javax.swing.JLabel txtDurationMinutes;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTarget;
    private javax.swing.JLabel txtTimeTotal;
    private javax.swing.JLabel txtTimeTotal1;
    private javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables

    
}